# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 3
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "daily"
      # Check for pnpm updates at 11am Central Time (Chicago)
      time: "11:00"
      timezone: "America/Chicago"
    commit-message:
      # Prefix all commit messages with "pnpm"
      prefix: "pnpm-package"
